serrurier_index:
    path:     /
    defaults: { _controller: "SerrurierBundle:Serrurier:index" }
    methods:  GET

serrurier_show:
    path:     /profil/{id}
    defaults: { _controller: "SerrurierBundle:Serrurier:show" }
    methods:  GET

serrurier_new:
    path:     /inscription
    defaults: { _controller: "SerrurierBundle:Serrurier:new" }
    methods:  [GET, POST]

serrurier_edit:
    path:     /edit/{id}
    defaults: { _controller: "SerrurierBundle:Serrurier:edit" }
    methods:  [GET, POST]

serrurier_delete:
    path:     /delete/{id}
    defaults: { _controller: "SerrurierBundle:Serrurier:delete" }
    methods:  DELETE

serrurier_planning:
    path: /planning/{id}
    defaults: { _controller: "SerrurierBundle:Serrurier:showPlanning" }
    methods:  GET
