<?php

namespace SerrurierBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SerrurierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerrurierRepository extends EntityRepository
{
}
