serrurier:
    resource: "@SerrurierBundle/Resources/config/routing.yml"
    prefix:   /serrurier

page:
    resource: "@PageBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
