serrurier:
    resource: "@SerrurierBundle/Resources/config/routing.yml"
    prefix:   /

page:
    resource: "@PageBundle/Resources/config/routing.yml"
    prefix:   /page

homepage:
  path: /
  defaults:
    _controller: AppBundle:Default:index

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
