page_homepage:
    path:     /
    defaults: { _controller: PageBundle:Default:index }

page_cgu:
  path: /conditions-utilisations
  defaults: { _controller: PageBundle:Page:cgu }

page_ml:
  path: /mentions-legales
  defaults: { _controller: PageBundle:Page:ml }

page_faq:
  path: /faq
  defaults: { _controller: PageBundle:Page:faq }