SerrurierBundle\Entity\Planning:
    type: entity
    table: null
    repositoryClass: SerrurierBundle\Repository\PlanningRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        debutIntervention:
            type: datetime
        finIntervention:
            type: datetime

    lifecycleCallbacks: {  }
