SerrurierBundle\Entity\Serrurier:
    type: entity
    table: null
    repositoryClass: SerrurierBundle\Repository\SerrurierRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: '40'
        prenom:
            type: string
            length: '40'
        societe:
            type: string
            length: '80'
        telephone:
            type: string
            length: '10'
        email:
            type: string
            length: '80'
        password:
             type: string
             length: '250'

    oneToOne:
        planning:
            targetEntity: SerrurierBundle\Entity\Planning
#
#    oneToMany:
#        adresse:
#            targetEntity: SerrurierBundle\Entity\Adresse
#            mappedBy: SerrurierBundle\Entity\Serrurier

    lifecycleCallbacks: {  }
