SerrurierBundle\Entity\Serrurier:
    type: entity
    table: null
    repositoryClass: SerrurierBundle\Repository\SerrurierRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: '40'
        prenom:
            type: string
            length: '40'
        societe:
            type: string
            length: '80'
        telephone:
            type: integer
            length: '10'
        adresse:
            type: string
            length: '250'
        ville:
            type: string
            length: '40'
        codePostal:
             type: string
             length: '5'
    lifecycleCallbacks: {  }
